version: '3.8'

services:

  my-redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - go_network


  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081" 
    environment:
      - REDIS_HOSTS=my-redis
    restart: unless-stopped
    networks:
      - go_network


  mongo_db:
    image: mongo:4.2.12
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - ./mongoconfig/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    ports:
      - "27017:27017"
    networks:
      - go_network


  mongo_express:
    image: mongo-express:0.54.0
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=mydb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=myuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mypassword
    ports:
      - "8083:8081"
    restart: on-failure
    depends_on:
      - mongo_db
    networks:
      - go_network

  nats:
    image: nats:latest
    ports:
      - "4222:4222"  # NATS server port
      - "6222:6222"  # NATS server cluster port
      - "8222:8222"  # NATS server monitoring port    
    networks:
      - go_network

  # app:
  #   build:
  #     context: ..
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mongo_db
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - go_network
  #   restart: always

  # ganache:
  #   image: trufflesuite/ganache-cli:latest
  #   ports:
  #     - "8545:8545"  # Expose Ganache RPC port
  #   command: >
  #     --account="0x39573730f7a6330869d9395c553fe17c4e2d95378b8c56e3e6bf818bbc8261f1,100000000000000000000" 

  #   networks:
  #     - go_network

  # truffle:
  #   build: 
  #     context: ./truffleDeploy
  #     dockerfile: Dockerfile
  #   networks:
  #     - go_network
  #   depends_on:
  #     - ganache
  #   #working_dir: /usr/src/app
  #   command: truffle migrate --network development

networks:
  go_network:
    driver: bridge
