version: '3.8'

services:
  mongo_db:
    image: mongo:4.2.12
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - ./mongoconfig/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    ports:
      - "27017:27017"
    networks:
      - go_network

  mongo_express:
    image: mongo-express:0.54.0
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=mydb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=myuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mypassword
    ports:
      - "8083:8081"
    restart: on-failure
    depends_on:
      - mongo_db
    networks:
      - go_network

  # app:
  #   build:
  #     context: ..
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mongo_db
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - go_network
  #   restart: always

networks:
  go_network:
    driver: bridge
